/* Create Table JSON Payload Example
{
   "TableName":"Music",
   "AttributeDefinitions":[
      {
         "AttributeName":"Artist",
         "AttributeType":"S"
      },
      {
         "AttributeName":"SongTitle",
         "AttributeType":"S"
      }
   ],
   "KeySchema":[
      {
         "AttributeName":"Artist",
         "KeyType":"HASH"
      },
      {
         "AttributeName":"SongTitle",
         "KeyType":"RANGE"
      }
   ],
   "ProvisionedThroughput":{
      "ReadCapacityUnits":"5",
      "WriteCapacityUnits":"5"
   },
   "LocalSecondaryIndexes":[
      {
         "IndexName":"AlbumTitle",
         "KeySchema":[
            {
               "AttributeName":"AlbumTitle",
               "KeyType":"RANGE"
            }
         ]
      }
   ],
   "GlobalSecondaryIndexes":[
      {
         "IndexName":"Genre/AlbumTitle",
         "KeySchema":[
            {
               "AttributeName":"Genre",
               "KeyType":"HASH"
            },
            {
               "AttributeName":"AlbumTitle",
               "KeyType":"RANGE"
            }
         ],
         "ProvisionedThroughput":{
            "ReadCapacityUnits":"5",
            "WriteCapacityUnits":"5"
         }
      }
   ]
}
*/
